# Generated by Django 5.2.14 on 2026-06-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='对应内容平台鞋类目的标准编码(如 sneakers)', max_length=64, verbose_name='类目编码'),
        ),
        migrations.AddField(
            model_name='category',
            name='l1_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='所属一级类目编码;一级类目自身则与 code 相同', max_length=64, verbose_name='一级类目编码'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_no',
            field=models.CharField(blank=True, db_index=True, default='', help_text='同款不同色码共享款号,用于聚合成鞋款(过渡方案)', max_length=64, verbose_name='款号'),
        ),
    ]
