# Generated by Django 5.2.14 on 2026-06-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_category_code_category_l1_code_product_model_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audience',
            field=models.CharField(blank=True, choices=[('', '不限'), ('female', '女性'), ('male', '男性'), ('student', '学生'), ('office', '职场通勤'), ('mom', '年轻妈妈'), ('all', '通用')], default='', max_length=16, verbose_name='目标人群'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, choices=[('', '不限'), ('spring', '春季'), ('summer', '夏季'), ('autumn', '秋季'), ('winter', '冬季'), ('all', '四季通用')], default='', max_length=16, verbose_name='适穿季节'),
        ),
    ]
