# Generated by Django 5.2.14 on 2026-06-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_audience_product_brand_product_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('main', '白底主图'), ('side', '侧面图'), ('sole', '鞋底图'), ('detail', '细节特写'), ('on_foot', '上脚穿搭')], default='main', max_length=20, verbose_name='图片类型'),
        ),
    ]
