# Generated by Django 5.2.14 on 2026-06-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventorytransaction_supplier_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='transaction_date',
            field=models.DateField(blank=True, help_text='实际进货/退货日期(单据上的日期),留空则用操作时间', null=True, verbose_name='业务日期'),
        ),
    ]
