# Generated by Django 5.2.14 on 2026-06-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_inventorytransaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='', help_text='自由输入,如 黑色/米白/黑白拼色', max_length=20, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='', help_text='自由输入,如 39/40.5/均码', max_length=10, verbose_name='尺码'),
        ),
    ]
