# Generated by Django 5.2.14 on 2026-06-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='warning_level',
            field=models.IntegerField(default=1, verbose_name='预警数量'),
        ),
    ]
