# Generated by Django 5.2.14 on 2026-06-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_inventory_warning_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='COMPLETED', max_length=20, verbose_name='状态'),
        ),
    ]
