# Generated by Django 5.2.14 on 2026-06-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scan_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='供扫码枪扫描的纯数字码(EAN-13),贴纸打印用;与商品条码(可含款号色码)分离', max_length=20, verbose_name='扫码码(贴纸条码)'),
        ),
    ]
