# Generated by Django 5.2.14 on 2026-06-27 23:59

import inventory.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_delete_color_delete_size_remove_stockalert_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.product.product_image_path, verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=inventory.models.product.product_image_path, verbose_name='图片'),
        ),
    ]
