# Generated by Django 5.2.14 on 2026-07-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='可选;为空时吊牌只显示售价一档', max_digits=10, null=True, verbose_name='折后价'),
        ),
    ]
